var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                           o                                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                         xx xx                                  ",
   "                                        x!!x!!x                                 ",
   "                                       x!!!!!!!x                           xxx  ",
   "                                        x!!!!!x                 o            x  ",
   "                                         x!!!x                               x  ",
   "                                  #       x!x                                x  ",
   "                                          xvx                                x  ",
   "                               yyyy                                          x  ",
   "  xxx                                                  yyyyy                 x  ",
   "  x                                        o                                 x  ",
   "  x                                                                          x  ",
   "  x                                                                +      o  x  ",
   "  x                    xxxx                                                  x  ",
   "  x                    x!!x  o     o  xxxxxxxxxxx                            x  ",
   "  x                    x!!x     o     x              yy          xx~xx       x  ",
   "  x  @                 x!!x           x                          x   x       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxx   xxxxxxxxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                           x!!!x          x!xxxxxxxxxxxxxxxxx!x   ",
   "                                                                  xxxxxxxxxx!!!x          xxx                x!x  ",
   "                                                                 x!!!!!!!!!!!!x                |             x!x  ",
   "                                                                 x!!!!!!!!!!!!x                      o       x!x  ",
   "                                               xx                x!!xxxxxxxxxx                 o            x!!!x ",
   "                                               xx                x!xxxxxxxxxxx                       |      x!!!x ",
   "                                               xx                xvxx                 #   xxx               x!!!x ",
   "                                     o         xx                   x  o                  x xxxxxxxxxxxx  o  x!x  ",
   "                                               xx                   x         +           x            x     xvx  ",
   "                                         yyy   xx                   x  o                 xx            x     x    ",
   "                  o                            xx                   x                    x             x     x    ",
   "                                               xx                   xxxxxxx      xxxxx~xxx             x     x    ",
   "                                yyy            xx                        xx      xx                    x  o  x    ",
   "                                        o      xx                        xx      xx                    x     x    ",
   "                                               xx                 +      xx      xx                    x     x    ",
   "                                               xx                        xx      xx                    x     x    ",
   "                      xx                       xx                        xxxx    xx                    x     x    ",
   "             xx       xx                yyy    xx      #                 xx      xx                    x  o  x    ",
   "     @       xx       xx                       xx                   xx   xx      xx                    x     x    ",
   "    xxx      xx       xx                       xx    xxx    yyy      x   xx      xx                   xx     x    ",
   "    xxx      xx       xx       xxx~xxx         xx    x               x   xx      xx       xxxxxxxxxxxxx      x    ",
   "!!!!xxx!!!!!!xx!!!!!!!xx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x   xx    xxxx      x          |     #  x    ",
   "!!!!xxx!!!!!!xx!!!!!!!xx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     x   xx      xx      x o     o           x    ",
   "!!!!xxx!!!!!!xx!!!!!!!xx!!!!!x                      xx!!!!!!xx !     x       o   xx      x                  xx    ",
   "xxxxxxx!!!!!!xx!!!!!!!xx!!!!!x    o                 x!!!!!!xx  !     x           xx      x                  x     ",
   "xxxxxxx!!!!!!xx!!!!!!!xx!!!!!x                     xx!!!!!!x   !     x     =     xx      x    o             x     ",
   "xxxxxxx!!!!!!xx!!!!!!!xx!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !     xxxxxxxxxxxxxx      x                 xx     ",
   "xxxxxxx!!!!!!xx!!!!!!!xx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                          xxxxxxxxxxxxxxxxxx!!!!!!",
   "xxxxxxx!!!!!!xx!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                          x!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                           v                                                                                   ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "  xxxxxxxx                                                                                                     ",
   "  x                                                                                       xxxxxxxxxx           ",
   "  x                                                                                       x        x           ",
   "  x                                                                                           o    x           ",
   "  x  @                                                                                              xxxxx      ",
   "  x                                                                       xxxxxxxxxxxxxxx               x      ",
   "  xxxxxxxx                                                    xx          x                             x      ",
   "  xx!!!!xx         #               #                           xxxxxx xxxxx  +           o         o    x      ",
   "    x!!x x                                                          x x                                 x      ",
   "    xvvx x        yyy             yyy                         #     xxx      xx  yyyy  yyy  yy~yy  yyyyyx      ",
   "         x                 o                                                 x                                 ",
   "         x                                                     xxx   o   xxxxx                                 ",
   "         x    o            y            o                     xx x       x                                     ",
   "         x                                                xx     xxxxxxxxx                                     ",
   "         x   yyy                       yyy                                                                     ",
   "         x    v                                                                                                ",
   "         x           o           o                                                                             ",
   "         x                                           xx                                                        ",
   "         x          yyy         yyy                                                                            ",
   "         x           v           v                                               x                             ",
   "         x                 o                                      xx                    x                      ",
   "         x                                                xx              x                    x               ",
   "         x                yyy                                                                                  ",
   "    x !!!x                 v                                                               o                   ",
   "    x!!xxx                                                        ||                                 x         ",
   "   xxxxx          x     x     x     x                                                                          ",
   "   x             xx!!!!!xx   xx!!!!!xx                                           x                             ",
   "   x  #          xxxxxxxxx   xxxxxxxxx          +         ||             +                                      ",
   "   x             x       x!!!x       x                            xx                    x      x               ",
   "   xxx~xxx    xxxx   o   xxxxx   o   xxxx      xxxxx      xx            xxx                                    ",
   "         x                                     x   x                    xxx                                    ",
   "         x                                     x   x!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "         x=                                   =x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                               "],

  ["                                                                                                                ",
   "                                                                                                                ",
   "                                          o o                                                                   ",
   "                                                                                                                ",
   "                                      xxxxxxxxxxxx                                                              ",
   "                                    xx            xx                                                            ",
   "                                   xx               x                                                           ",
   "                               # xxx                x                                                           ",
   "                                                    x     yyyyyy                                                ",
   "             x= =                       o  xyy      x                                                           ",
   "             x          oo        = =   o  x        x                                                           ",
   "                                    x      x      yyx               yyyy                                        ",
   "  x                    yyyy         x      x        xxx                                 o                       ",
   "  x          x                    = =   o  x          xxx                   yyyy                                ",
   "  x          x                          o  x o          x                              x x                      ",
   "  x          x= =                          x           #x                             x!x!x                     ",
   "  x          x                     xx      xxxx         x                              x!x                      ",
   "  x          xxxxxx~xxxxxxxxxxxxxxxx       x!xxyy       x                         o     x                       ",
   "  x                                x       x!xx         x                                                       ",
   "  x                                x    xxxxvxx         x                                                       ",
   "  x                                x          x         x                        x x                            ",
   "  x                                x    o     x       yyx                       x!x!x                           ",
   "  x                                x          x         x               o        x!x                            ",
   "  x                                x          x         x                         x                             ",
   "  x                                xxxxxxxxx xx         x                                                       ",
   "  x                                xxx!xxxx!!!xyy       x              x x                                      ",
   "  x                                xx!!!xxxx!xx         x             x!x!x                                     ",
   "  x                                xxxvxx xxxxx         x              x!x                                      ",
   "  x                                x                    x               x       o                               ",
   "  x                                x          +         x                                                       ",
   "  x                                x                yyyyx                                                       ",
   "  x   x   x                        x  o                 x                      xxx                              ",
   "  x   x   x                        x                    x                     x!!!x                             ",
   "  x  x  @  x                       x                    x                      xvx                              ",
   "  x  x     x                       x                  o x                                                       ",
   "  x  xxxxxxx                       xxx xxxxx xx         x!!!!!!!!!!!!!!!!!!             o                       ",
   "  x   x!!!x                        xxx!xxxxx!xx     xxxxxxxxxxxxxxxxxxxxxx!                                     ",
   "  x    xvx                         xx!!!xxx!!!x                          x!            xxx                      ",
   "  x                                xxxxxxxxxxxx                          x!           x!!!x            xxx xxx  ",
   "  x                                x    |   x                            x!            xvx                x     ",
   "  x                                x        xxxxxx              oo       x!                              xxx    ",
   "  x               o                         x         oo                 x!             +               x   x   ",
   "  x                                  o     o                   yyyy    + x!                                  x  ",
   "  x  o                                  o           |yyyy|    |    |     x!        yy       yy            o  x  ",
   "  x                                                                    o x!                                  x  ",
   "  x  o                            xxxxxxxxxxxx                           x!    #                   y    x   x   ",
   "  x                              xxxxxxxxxxxxxxxx                      o x!                              x~x    ",
   "  x  o                          xxxxxxxxxxxxxxxxxx  x    x    x    x     x!                               x     ",
   "  x             x   x          =xxxxxxxxxxxxxxxxxx  x    x    x    x  xxxx!  xxxxx                              ",
   "  xxxxx   xxxxxxx!!!xxxxx~xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "      x!!!x      x!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "       x!x        x             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "  x      # o     o  oooo  o    o       o       o  ooo  o    o  o   #         x  ",
    "  x      +  o   o  o    o o    o       o       o   o   oo   o  o   +         x  ",
    "  x      #   ooo   o    o o    o   +   o   o   o   o   o o  o  o   #         x  ",
    "  x      +    o    o    o o    o       o   o   o   o   o  o o  o   +         x  ",
    "  x      #    o    o    o o    o       o   o   o   o   o   oo      #         x  ",
    "  x      +    o     oooo   oooo         ooo ooo   ooo  o    o  o   +         x  ",
    "  x      #                                                         #         x  ",
    "  x      yyyyyyyyyyyyyyyyyyyyyyyyyy~yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy         x  ",
    "  x                                                                          x  ",
    "  x  @   = = = =                                                     = = = = x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                ",
],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
